import * as t from 'drizzle-orm/pg-core';
import { pgTable as table } from 'drizzle-orm/pg-core';

export const pool = table('pools', {
  id: t.integer().primaryKey().generatedAlwaysAsIdentity(),
  createdAtBlock: t.integer('created_at_block').notNull(),
  createdAtTimestamp: t.integer('created_at_timestamp').notNull(),
  transaction: t.text().notNull(),
  jetton0: t.text().notNull(),
  jetton1: t.text().notNull(),
  feeTier: t.integer('fee_tier').notNull(),
  feeProtocol: t.integer('fee_protocol').notNull(),
  liquidity: t.text().notNull(),
  sqrtPrice: t.text('sqrt_price').notNull(),
  feeGrowthGlobal0X128: t.text('fee_growth_global_0x128').notNull(),
  feeGrowthGlobal1X128: t.text('fee_growth_global_1x128').notNull(),
  tick: t.integer().notNull(),
  feesUSD: t.text('fees_usd').notNull(),
  protocolFeesUSD: t.text('protocol_fees_usd').notNull(),
  collectedFeesJetton0: t.text('collected_fees_jetton0').notNull(),
  collectedFeesJetton1: t.text('collected_fees_jetton1').notNull(),
  collectedFeesUSD: t.text('collected_fees_usd').notNull(),
  totalValueLockedJetton0: t.text('total_value_locked_jetton0').notNull(),
  totalValueLockedJetton1: t.text('total_value_locked_jetton1').notNull(),
  totalValueLockedTon: t.text('total_value_locked_ton').notNull(),
  totalValueLockedUSD: t.text('total_value_locked_usd').notNull(),
  jetton0Price: t.text('jetton0_price').notNull(),
  jetton1Price: t.text('jetton1_price').notNull(),
  volume0: t.text().notNull(),
  volume1: t.text().notNull(),
  volumeUSD: t.text('volume_usd').notNull(),
  txCount: t.integer('tx_count').notNull(),
  liquidityProviderCount: t.integer('liquidity_provider_count').notNull(),
});
